version: '3.1'

services:
  core_db:
   container_name: core_db
   image: postgres
   environment:
    POSTGRES_DB: core_db
    POSTGRES_USER: core_user
    POSTGRES_PASSWORD: core_user
   ports:
     - "5433:5432"
   volumes:
     - postgres:/data/postgres
   healthcheck:
    test: [ "CMD-SHELL", "pg_isready -U core_user" ]
    interval: 10s
    timeout: 5s
    retries: 5
   restart: unless-stopped

  core-service:
   container_name: core-api
   build: .
   environment:
     SPRING_DATASOURCE_URL: jdbc:postgresql://core_db:5433/core_db
   ports:
     - "8080:8080"
   depends_on:
     core_db:
      condition: service_healthy
volumes:
  postgres: